### PR TITLE
Add integration service + receiver to AndroidManifest.

### PR DESCRIPTION
**Pull request by hvisser**
Gradle automatically merges the manifest of the lib project into an app project. This skips the step of adding the receiver and service to the app manifest and reduces errors.

### CODE REVIEW

**Comment by jgilfelt** [comment]
Thanks! I had no idea Gradle worked like this - I assume it is an .aar thing? 

I'm also distributing a JAR (yes some of us still use Ant) so I'll need to update the integration instructions accordingly.

**Comment by hvisser** [comment]
Yes, that will only work for .aar packaging, jar's don't have the manifest or other resources packaged. I'm not sure if it will also work for Maven users, but but they now support .aar packaging as well I believe.

**Comment by jgilfelt** [comment]
Fuck Maven users.

**Comment by hvisser** [comment]
I owe you a beer now.

**Pull request merged**
